#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  anon_sym_BSLASH = 6,
  anon_sym_SLASH = 7,
  anon_sym_PIPE = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_EQ = 11,
  sym_literal_unquoted = 12,
  sym_literal_unquoted_feat = 13,
  sym_literal_quoted = 14,
  sym_source_file = 15,
  sym_cat_funcapp = 16,
  sym_cat_functor_arg_list = 17,
  sym_cat_left = 18,
  sym_cat_right = 19,
  sym_cat_middle = 20,
  sym_cat_uniq = 21,
  sym_cat_name = 22,
  sym_feature_list = 23,
  sym_feature = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_cat_functor_arg_list_repeat1 = 26,
  aux_sym_feature_list_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_SLASH] = "/",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [sym_literal_unquoted] = "literal_unquoted",
  [sym_literal_unquoted_feat] = "literal_unquoted_feat",
  [sym_literal_quoted] = "literal_quoted",
  [sym_source_file] = "source_file",
  [sym_cat_funcapp] = "cat_funcapp",
  [sym_cat_functor_arg_list] = "cat_functor_arg_list",
  [sym_cat_left] = "cat_left",
  [sym_cat_right] = "cat_right",
  [sym_cat_middle] = "cat_middle",
  [sym_cat_uniq] = "cat_uniq",
  [sym_cat_name] = "cat_name",
  [sym_feature_list] = "feature_list",
  [sym_feature] = "feature",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_cat_functor_arg_list_repeat1] = "cat_functor_arg_list_repeat1",
  [aux_sym_feature_list_repeat1] = "feature_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_literal_unquoted] = sym_literal_unquoted,
  [sym_literal_unquoted_feat] = sym_literal_unquoted_feat,
  [sym_literal_quoted] = sym_literal_quoted,
  [sym_source_file] = sym_source_file,
  [sym_cat_funcapp] = sym_cat_funcapp,
  [sym_cat_functor_arg_list] = sym_cat_functor_arg_list,
  [sym_cat_left] = sym_cat_left,
  [sym_cat_right] = sym_cat_right,
  [sym_cat_middle] = sym_cat_middle,
  [sym_cat_uniq] = sym_cat_uniq,
  [sym_cat_name] = sym_cat_name,
  [sym_feature_list] = sym_feature_list,
  [sym_feature] = sym_feature,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_cat_functor_arg_list_repeat1] = aux_sym_cat_functor_arg_list_repeat1,
  [aux_sym_feature_list_repeat1] = aux_sym_feature_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_literal_unquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_unquoted_feat] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_funcapp] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_functor_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_left] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_right] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_middle] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_uniq] = {
    .visible = true,
    .named = true,
  },
  [sym_cat_name] = {
    .visible = true,
    .named = true,
  },
  [sym_feature_list] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cat_functor_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_antecedent = 1,
  field_arguments = 2,
  field_consequent = 3,
  field_functor = 4,
  field_key = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_antecedent] = "antecedent",
  [field_arguments] = "arguments",
  [field_consequent] = "consequent",
  [field_functor] = "functor",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 1},
    {field_functor, 0},
  [2] =
    {field_antecedent, 0},
    {field_consequent, 2},
  [4] =
    {field_antecedent, 2},
    {field_consequent, 0},
  [6] =
    {field_key, 0},
  [7] =
    {field_antecedent, 0},
    {field_consequent, 3},
  [9] =
    {field_antecedent, 3},
    {field_consequent, 0},
  [11] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 13,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 42,
  [45] = 41,
  [46] = 29,
  [47] = 24,
  [48] = 22,
  [49] = 43,
  [50] = 26,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 51,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '\'', 3,
        '(', 10,
        ')', 12,
        ',', 11,
        '/', 14,
        '<', 8,
        '=', 18,
        '>', 9,
        '[', 16,
        '\\', 13,
        ']', 17,
        '|', 15,
      );
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '<') ADVANCE(8);
      if (lookahead == '[') ADVANCE(16);
      if (lookahead == '~') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == ']') ADVANCE(17);
      if (lookahead == '~') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '~') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '~') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_literal_unquoted);
      if (lookahead == '~') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '<' &&
          lookahead != '>' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_literal_unquoted_feat);
      if (lookahead == '~') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_literal_quoted);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_literal_quoted);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '~') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_literal_quoted] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(40),
    [sym_cat_funcapp] = STATE(35),
    [sym_cat_left] = STATE(35),
    [sym_cat_right] = STATE(35),
    [sym_cat_middle] = STATE(35),
    [sym_cat_uniq] = STATE(35),
    [sym_cat_name] = STATE(9),
    [anon_sym_LT] = ACTIONS(3),
    [sym_literal_unquoted] = ACTIONS(5),
    [sym_literal_quoted] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_cat_name,
    STATE(23), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(3), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [28] = 7,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_cat_name,
    STATE(34), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(39), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [56] = 7,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_cat_name,
    STATE(33), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(39), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [84] = 7,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_cat_name,
    STATE(32), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(39), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [112] = 7,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_cat_name,
    STATE(20), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(5), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [140] = 7,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_cat_name,
    STATE(21), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(4), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [168] = 6,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_cat_name,
    STATE(37), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [192] = 3,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(14), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [210] = 3,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(13), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(15), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [228] = 6,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_cat_name,
    STATE(36), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [252] = 3,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(17), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(19), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [270] = 3,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    STATE(13), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [288] = 3,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(13), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(26), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [306] = 3,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(10), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(28), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [324] = 6,
    ACTIONS(3), 1,
      anon_sym_LT,
    ACTIONS(30), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_cat_name,
    STATE(37), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [348] = 3,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(13), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(32), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [366] = 5,
    ACTIONS(3), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_cat_name,
    STATE(38), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [387] = 5,
    ACTIONS(3), 1,
      anon_sym_LT,
    STATE(9), 1,
      sym_cat_name,
    STATE(37), 1,
      sym_source_file,
    ACTIONS(5), 2,
      sym_literal_unquoted,
      sym_literal_quoted,
    STATE(35), 5,
      sym_cat_funcapp,
      sym_cat_left,
      sym_cat_right,
      sym_cat_middle,
      sym_cat_uniq,
  [408] = 6,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_BSLASH,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    ACTIONS(34), 4,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [430] = 2,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    ACTIONS(44), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [444] = 1,
    ACTIONS(46), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [456] = 2,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    ACTIONS(48), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [470] = 1,
    ACTIONS(50), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [482] = 1,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [494] = 1,
    ACTIONS(54), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [506] = 1,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [518] = 1,
    ACTIONS(58), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [530] = 1,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [542] = 1,
    ACTIONS(62), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [554] = 1,
    ACTIONS(64), 9,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
      anon_sym_LBRACK,
  [566] = 6,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_BSLASH,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [588] = 2,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    ACTIONS(68), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [602] = 2,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [616] = 1,
    ACTIONS(72), 8,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_SLASH,
      anon_sym_PIPE,
  [627] = 8,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_BSLASH,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    STATE(53), 1,
      aux_sym_cat_functor_arg_list_repeat1,
  [652] = 6,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_BSLASH,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      sym_cat_functor_arg_list,
    ACTIONS(78), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [672] = 6,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_BSLASH,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    ACTIONS(80), 1,
      anon_sym_GT,
    STATE(12), 1,
      sym_cat_functor_arg_list,
  [691] = 3,
    ACTIONS(82), 1,
      anon_sym_LBRACK,
    STATE(39), 2,
      sym_feature_list,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 3,
      anon_sym_LT,
      sym_literal_unquoted,
      sym_literal_quoted,
  [704] = 6,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_BSLASH,
    ACTIONS(40), 1,
      anon_sym_SLASH,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      sym_cat_functor_arg_list,
  [723] = 3,
    ACTIONS(87), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      sym_feature,
    ACTIONS(89), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
  [734] = 3,
    ACTIONS(91), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      sym_feature,
    ACTIONS(89), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
  [745] = 3,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      sym_feature,
    ACTIONS(89), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
  [756] = 3,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      sym_feature,
    ACTIONS(89), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
  [767] = 3,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      sym_feature,
    ACTIONS(89), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
  [778] = 1,
    ACTIONS(60), 4,
      anon_sym_LT,
      anon_sym_LBRACK,
      sym_literal_unquoted,
      sym_literal_quoted,
  [785] = 1,
    ACTIONS(50), 4,
      anon_sym_LT,
      anon_sym_LBRACK,
      sym_literal_unquoted,
      sym_literal_quoted,
  [792] = 1,
    ACTIONS(46), 4,
      anon_sym_LT,
      anon_sym_LBRACK,
      sym_literal_unquoted,
      sym_literal_quoted,
  [799] = 3,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      sym_feature,
    ACTIONS(89), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
  [810] = 1,
    ACTIONS(54), 4,
      anon_sym_LT,
      anon_sym_LBRACK,
      sym_literal_unquoted,
      sym_literal_quoted,
  [817] = 3,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
    STATE(59), 1,
      aux_sym_feature_list_repeat1,
  [827] = 2,
    STATE(60), 1,
      sym_feature,
    ACTIONS(89), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
  [835] = 3,
    ACTIONS(9), 1,
      anon_sym_RPAREN,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_cat_functor_arg_list_repeat1,
  [845] = 3,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RBRACK,
    STATE(54), 1,
      aux_sym_feature_list_repeat1,
  [855] = 2,
    ACTIONS(114), 1,
      anon_sym_EQ,
    ACTIONS(112), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [863] = 3,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_cat_functor_arg_list_repeat1,
  [873] = 3,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      aux_sym_feature_list_repeat1,
  [883] = 3,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_feature_list_repeat1,
  [893] = 3,
    ACTIONS(91), 1,
      anon_sym_RBRACK,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_feature_list_repeat1,
  [903] = 1,
    ACTIONS(110), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [908] = 1,
    ACTIONS(127), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [913] = 1,
    ACTIONS(129), 2,
      sym_literal_unquoted_feat,
      sym_literal_quoted,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 168,
  [SMALL_STATE(9)] = 192,
  [SMALL_STATE(10)] = 210,
  [SMALL_STATE(11)] = 228,
  [SMALL_STATE(12)] = 252,
  [SMALL_STATE(13)] = 270,
  [SMALL_STATE(14)] = 288,
  [SMALL_STATE(15)] = 306,
  [SMALL_STATE(16)] = 324,
  [SMALL_STATE(17)] = 348,
  [SMALL_STATE(18)] = 366,
  [SMALL_STATE(19)] = 387,
  [SMALL_STATE(20)] = 408,
  [SMALL_STATE(21)] = 430,
  [SMALL_STATE(22)] = 444,
  [SMALL_STATE(23)] = 456,
  [SMALL_STATE(24)] = 470,
  [SMALL_STATE(25)] = 482,
  [SMALL_STATE(26)] = 494,
  [SMALL_STATE(27)] = 506,
  [SMALL_STATE(28)] = 518,
  [SMALL_STATE(29)] = 530,
  [SMALL_STATE(30)] = 542,
  [SMALL_STATE(31)] = 554,
  [SMALL_STATE(32)] = 566,
  [SMALL_STATE(33)] = 588,
  [SMALL_STATE(34)] = 602,
  [SMALL_STATE(35)] = 616,
  [SMALL_STATE(36)] = 627,
  [SMALL_STATE(37)] = 652,
  [SMALL_STATE(38)] = 672,
  [SMALL_STATE(39)] = 691,
  [SMALL_STATE(40)] = 704,
  [SMALL_STATE(41)] = 723,
  [SMALL_STATE(42)] = 734,
  [SMALL_STATE(43)] = 745,
  [SMALL_STATE(44)] = 756,
  [SMALL_STATE(45)] = 767,
  [SMALL_STATE(46)] = 778,
  [SMALL_STATE(47)] = 785,
  [SMALL_STATE(48)] = 792,
  [SMALL_STATE(49)] = 799,
  [SMALL_STATE(50)] = 810,
  [SMALL_STATE(51)] = 817,
  [SMALL_STATE(52)] = 827,
  [SMALL_STATE(53)] = 835,
  [SMALL_STATE(54)] = 845,
  [SMALL_STATE(55)] = 855,
  [SMALL_STATE(56)] = 863,
  [SMALL_STATE(57)] = 873,
  [SMALL_STATE(58)] = 883,
  [SMALL_STATE(59)] = 893,
  [SMALL_STATE(60)] = 903,
  [SMALL_STATE(61)] = 908,
  [SMALL_STATE(62)] = 913,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_uniq, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_funcapp, 2, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_uniq, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_funcapp, 3, 0, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_left, 3, 0, 2),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_right, 3, 0, 3),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_list, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_middle, 3, 0, 3),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_list, 4, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_functor_arg_list, 5, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_list, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_functor_arg_list, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_functor_arg_list, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_list, 5, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_name, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_functor_arg_list, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_left, 4, 0, 5),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_right, 4, 0, 6),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cat_middle, 4, 0, 6),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cat_functor_arg_list_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_list_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_list_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 1, 0, 4),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cat_functor_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 3, 0, 7),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_CategorialGrammarIconic(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
